version: '3.8'

services:
  api:
    build: .
    container_name: realin-api
    ports:
      - "8080:8080"
    env_file:
      - .env.development
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
