namespace RealinApi.Features.Property.Models;

public record CreatePropertyRequest(
    string Title,
    string ListingType,
    string ListingCategory,
    string PropertyType,
    string ConstructionStatus,
    string Facing,
    decimal Price,
    Guid AgentId,
    Guid? ProjectId = null,
    string? ReraId = null,
    DateTime? AvailableFrom = null,
    string? Address = null,
    string? Locality = null,
    string? City = null,
    string? PinCode = null,
    string? Landmark = null,
    double? Latitude = null,
    double? Longitude = null,
    int? FloorNumber = null,
    int? TotalFloors = null,
    string Currency = "INR",
    decimal? MonthlyRent = null,
    decimal? SecurityDeposit = null,
    decimal? MaintenanceCharges = null,
    bool? PriceNegotiable = null,
    decimal? CarpetArea = null,
    decimal? BuiltupArea = null,
    decimal? SuperBuiltupArea = null,
    int? Bedrooms = null,
    int? Bathrooms = null,
    int? Balconies = null,
    string? FurnishingStatus = null,
    int? PropertyAge = null,
    string? OwnershipType = null,
    bool? LoanAvailable = null,
    string? VideoUrl = null,
    string? ImageUrl = null,
    string? Amenities = null,
    string? InteriorFeatures = null,
    string? Utilities = null,
    bool IsPublished = false,
    bool IsFeatured = false
);

public record UpdatePropertyRequest(
    string? Title = null,
    string? ListingType = null,
    string? ListingCategory = null,
    string? PropertyType = null,
    string? ConstructionStatus = null,
    string? Facing = null,
    decimal? Price = null,
    Guid? ProjectId = null,
    string? Status = null,
    string? ReraId = null,
    DateTime? AvailableFrom = null,
    string? Address = null,
    string? Locality = null,
    string? City = null,
    string? PinCode = null,
    string? Landmark = null,
    double? Latitude = null,
    double? Longitude = null,
    int? FloorNumber = null,
    int? TotalFloors = null,
    string? Currency = null,
    decimal? MonthlyRent = null,
    decimal? SecurityDeposit = null,
    decimal? MaintenanceCharges = null,
    bool? PriceNegotiable = null,
    decimal? CarpetArea = null,
    decimal? BuiltupArea = null,
    decimal? SuperBuiltupArea = null,
    int? Bedrooms = null,
    int? Bathrooms = null,
    int? Balconies = null,
    string? FurnishingStatus = null,
    int? PropertyAge = null,
    string? OwnershipType = null,
    bool? LoanAvailable = null,
    string? VideoUrl = null,
    string? ImageUrl = null,
    string? Amenities = null,
    string? InteriorFeatures = null,
    string? Utilities = null,
    bool? IsPublished = null,
    bool? IsFeatured = null
);

public record PropertyResponse(
    Guid Id,
    string Title,
    string ListingType,
    string ListingCategory,
    string PropertyType,
    string ConstructionStatus,
    string Facing,
    decimal Price,
    string Status,
    Guid AgentId,
    Guid? ProjectId,
    string? ReraId,
    DateTime? AvailableFrom,
    string? Address,
    string? Locality,
    string? City,
    string? PinCode,
    string? Landmark,
    double? Latitude,
    double? Longitude,
    int? FloorNumber,
    int? TotalFloors,
    string Currency,
    decimal? MonthlyRent,
    decimal? SecurityDeposit,
    decimal? MaintenanceCharges,
    bool? PriceNegotiable,
    decimal? CarpetArea,
    decimal? BuiltupArea,
    decimal? SuperBuiltupArea,
    int? Bedrooms,
    int? Bathrooms,
    int? Balconies,
    string? FurnishingStatus,
    int? PropertyAge,
    string? OwnershipType,
    bool? LoanAvailable,
    string? VideoUrl,
    string? ImageUrl,
    string? Amenities,
    string? InteriorFeatures,
    string? Utilities,
    bool IsPublished,
    bool IsFeatured,
    DateTime CreatedAt,
    DateTime UpdatedAt,
    AgentSummary? Agent = null,
    ProjectSummary? Project = null
);
